# Generated by Django 4.2.7 on 2023-12-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название продукта')),
                ('description', models.CharField(max_length=250, verbose_name='описание')),
                ('photo_preview', models.ImageField(upload_to='preview/', verbose_name='изображение (превью)')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('piece_price', models.BooleanField(verbose_name='цена за штуку')),
                ('creation_date', models.DateField(verbose_name='дата создания')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
